### ISSUE TITLE
fix string comparison

### ISSUE THREAD

**Issue by magwas** [edemo/PDEngine#186]
no testcase needed. Counts as 1 testcase.
https://sonarcloud.io/project/issues?branch=develop&id=org.rulez.demokracia%3APDEngine&open=AWjRti-NEzgCzR11fxzX

**Comment by valentinbujdoso** [comment]
If I say there is already fixed, can I get the 1 testcase? :)

**Comment by colorimeter** [comment]
Fixed since ages, but not optimally: the check of "type" should be outside of the for loop since it does not change. :)

**Comment by magwas** [comment]
No, it is not fixed, the code contains '==' instead of .equals(). That is the problem.

**Comment by valentinbujdoso** [comment]
I think what you see on sonarcloud is from February 9, 2019, 11:55 AM

**Comment by magwas** [comment]
oh, my.
You are right. Git blame even says that I have fixed it :)
Alzheimer makes you meet new people every day.
